#pragma once
#include "../../operator.h"
#include "info.h"

#define DESCRIPTOR(NAMESPACE)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \
    namespace op::mamba2_scan::NAMESPACE {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             \
    class Descriptor final : public InfiniopDescriptor {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               \
        Mamba2ScanInfo _info;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \
        size_t _workspace_size;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        \
        Descriptor(Mamba2ScanInfo info, size_t workspace_size, infiniDevice_t device_type, int device_id)                                                                                                                                                                                                                                                                                                                                                                                                                                                              \
            : InfiniopDescriptor{device_type, device_id}, _info(info), _workspace_size(workspace_size) {}                                                                                                                                                                                                                                                                                                                                                                                                                                                              \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       \
    public:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            \
        size_t workspaceSize() const { return _workspace_size; }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       \
        static infiniStatus_t create(infiniopHandle_t handle, Descriptor **desc_ptr, infiniopTensorDescriptor_t out_desc, infiniopTensorDescriptor_t x_desc, infiniopTensorDescriptor_t dt_desc, infiniopTensorDescriptor_t b_desc, infiniopTensorDescriptor_t c_desc, infiniopTensorDescriptor_t a_desc, infiniopTensorDescriptor_t d_desc, infiniopTensorDescriptor_t dt_bias_desc, infiniopTensorDescriptor_t state_desc, infiniopTensorDescriptor_t offsets_desc, infiniopTensorDescriptor_t initial_indices_desc, infiniopTensorDescriptor_t final_indices_desc); \
        infiniStatus_t calculate(void *workspace, size_t workspace_size, void *out, const void *x, const void *dt, const void *b, const void *c, const void *a, const void *d, const void *dt_bias, void *state, const void *offsets, const void *initial_indices, const void *final_indices, void *stream) const;                                                                                                                                                                                                                                                     \
    };                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 \
    }
