#ifndef DSV4_ADD_RMSNORM_QUANT_H
#define DSV4_ADD_RMSNORM_QUANT_H
#include "../../operator.h"
#include "info.h"
#define DESCRIPTOR(NAMESPACE)                                                                                                                                                                                                                                                                  \
    namespace op::dsv4_add_rmsnorm_quant::NAMESPACE {                                                                                                                                                                                                                                          \
    class Descriptor final : public InfiniopDescriptor {                                                                                                                                                                                                                                       \
        Info _info;                                                                                                                                                                                                                                                                            \
        float _epsilon;                                                                                                                                                                                                                                                                        \
        size_t _workspace_size;                                                                                                                                                                                                                                                                \
        Descriptor(Info info, float epsilon, size_t workspace_size, infiniDevice_t device_type, int device_id) : InfiniopDescriptor{device_type, device_id}, _info(info), _epsilon(epsilon), _workspace_size(workspace_size) {}                                                                \
                                                                                                                                                                                                                                                                                               \
    public:                                                                                                                                                                                                                                                                                    \
        size_t workspaceSize() const { return _workspace_size; }                                                                                                                                                                                                                               \
        const Info &info() const { return _info; }                                                                                                                                                                                                                                             \
        float epsilon() const { return _epsilon; }                                                                                                                                                                                                                                             \
        static infiniStatus_t create(infiniopHandle_t handle, Descriptor **desc_ptr, infiniopTensorDescriptor_t res_desc, infiniopTensorDescriptor_t q_desc, infiniopTensorDescriptor_t scale_desc, infiniopTensorDescriptor_t x_desc, infiniopTensorDescriptor_t weight_desc, float epsilon); \
        infiniStatus_t calculate(void *workspace, size_t workspace_size, void *res, void *q, void *scale, const void *x, const void *weight, void *stream) const;                                                                                                                              \
    };                                                                                                                                                                                                                                                                                         \
    }
#endif
